#!/usr/bin/python3
#########################
from string import Template

#Compile return codes
SUCCESS=0
MISMATCH_BRACKET=1
PROGRAMSIZE=2

header=Template("""#include <stdio.h>
#include <stdlib.h>
#define TAPESIZE $tapesz
/*Object file generated by the BFtoC compiler*/

int main(void) {
char * tape=malloc(sizeof(char)*TAPESIZE);
char * pointer=tape;

""")

footer="""free(tape);
return 0;
}
"""
class BracketStack:
	program=""
	bracket_level=0
		
	def __init__(self,program_):
		self.program=program_	
	def push(self):
		self.bracket_level+=1
	def pop(self):
		self.bracket_level-=1
	def checkBrackets(self):
		for c in self.program:
			if c is '[':
				self.push()
			elif c is ']':
				self.pop()
		if self.bracket_level is not 0:
			return 1
		else:
			return 0

 
class BrainFuckParser:
	program=""
	maxvalue=0
	maxprogramsize=0
	tapesize=0
	commandDict={">":"++pointer;\n", "<":"--pointer;\n", "+":"++*pointer;\n", "-":"--*pointer;\n", \
		".":"putchar(*pointer);\n", ",":"*pointer=getchar();\n", "[":"while (*pointer) {\n", "]":"}"} 
	return_code=0
	def __init__(self,program_,maxprogamsize_,tapesize_):
		self.program=program_
		#maxvalue=maxvalue_
		#self.maxprogramsize=maxprogramsize_
		self.tapesize=tapesize_
	def checkProgramSize(self):
		#TODO
		return 0		
	def checkBrackets(self):
		bracketChecker=BracketStack(self.program)
		if not bracketChecker.checkBrackets():
			return 0
		else:
			return 1

	def substitute(self,command):
		if (command in self.commandDict):
			return self.commandDict[command]
		else:
			return None
	def generateHeader(self):
		return header.substitute(tapesz=self.tapesize)	
	def compileProgram(self):
		returnTuple=None
		compiledCProg=None
		token=""
		if (self.checkProgramSize()):
			returnTuple=(PROGRAMSIZE,None)
			return returnTuple
		elif (self.checkBrackets()):
			returnTuple=(MISMATCH_BRACKET,None)
			return returnTuple
		compiledCProg=self.generateHeader()
		for c in self.program:
			token=self.substitute(c)
			if (token is not None):
				compiledCProg=compiledCProg+token
		
		compiledCProg=compiledCProg+footer
		returnTuple=(0,compiledCProg)
		return returnTuple
		
